---
title: "Replication of Study Robust holistic face processing in early childhood
during the COVID-19 pandemic by Yates & Lewkowicz (2023, Journal of Experimental Child Psychology)"
author: "Replication Author[s]: Anna Pusok (annapusok@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Autism spectrum disorder (ASD) is characterized by difficulties in social communication, repetitive behaviors and restricted interests. A fundamental aspect of social communication is face perception, which has been extensively studied in ASD research. The composite face effect (CFE; Young et al., 1987) is a measure of holistic face processing, and typically developing children show evidence of the CFE as early as four years of age. In contrast, individuals with ASD often exhibit atypical face processing, thought to stem from reduced holistic perception and employing more feature-based strategies. However, holistic face processing is cruical for social communication processes, such as emotion recognition. Although several studies have examined the CFE in adolescents and adults with ASD, findings have been inconsistent. To date, however, no research has investigated the CFE in young children with ASD. My first year project aims to fill this gap by testing holistic face processing in young children with ASD. As a first step, for my statistics project, I want to pilot the task with neurotypical adults to validate the paradigm and ensure the procedure is feasible before extending it to child populations. Yates & Lewkowicz tested the CFE paradigm in children ages 4-6, with findings that kids as young as 4 exhibit holistic face processing, so I am planning to replicate their study.

For the stimuli, I plan to use a Caucasian hairless faces (male and female) with neutral expressions, from the Chicago Face Database. The face images will be grayscale displayed on a white screen, and the top parts of the faces will be highlighted, consistent with prior (Yates & Lewkowicz, 2023). Yates & Lewkowicz presented 36 trials, for the adult sample, I plan to do more based on power analysis. //I will meet with Jane to discuss what is the best number of trials for the experiment based on power analysis. I do plan to use different analysis methods once I collect both neurotypical and ASD data given that Yates & Lewkowicz only had neurotypical kid data only and for the class, I'm only collecting neurotypical adult data.

The procedure will include two practice trials, the first one being spatially aligned composite faces where the top halves are of different faces, the other being spatially misaligned with same top halves. Participants will receive feedback during the practice trials, and the experiment only advances forward when participants select the correct choice. The test phase will consist of 2 blocks of 36 test trials with a short break between the blocks.

About 24 neurotypical adult participants will be recruited for the final project. This sample size was according to Hsiung & Chien (2024.) They conducted a power analysis and determined that 24 neurotypical and ASD adults are a good number. I uploaded that paper to my original_paper folder.

The main challenge will be ensuring that participants remain attentive through the trials. For that, I’ll be including an exclusion criteria that if participants said all “same” or all “different” responses, which would be an indicator of not paying attention. Participants who also fail to finish the experiment will also be excluded.

Link to paper: https://github.com/annapusok731/yates2023/tree/2885fd3f36660e431e4876c7b2f4dec89f9b7a79/original_paper

Repository: https://github.com/annapusok731/yates2023.git

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

For the adult sample, we are aiming for 24 neurotypical adults. This sample size is according to Hsiung & Chien (2024) who has done a study of the composite face effect in adults with ASD as well as neurotypical adults. They conducted a power analysis based on and determined that 24 neurotypical and ASD adults are a good number.

Exclusion criteria: Responses faster than 200 ms or slower than 4000 ms were excluded, removing only 2% of the trials. Participants will also be excluded if they had all “same” or all “different” responses, which would be an indicator of not paying attention.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Sona

The first part of the experiment consisted of two practice trials. During the first of these trials, participants saw a pair of spatially aligned composite faces where the top halves were of different faces. One composite face was presented on one side of the screen, and the other composite face was presented on the other side of the screen."
Adults are asked to decide whether the yellow parts of the faces (i.e., the tops) of these composite faces were the same or different. Participants will receive feedback during the practice trials. Thus an incroeect response will prompt them to "Try Again." A correct response will affirm them in their decisions: "Great job! The yellow parts of the face are the same." During the second practice trial, participants will see a pair of spatially misaligned composite faces where the top halves were of the same face and were once again asked whether the yellow parts” of these faces were the same or different. Again, if participants made an incorrect choice, they will be prompted to try again, and they got positive response for the correct choice.

As soon as the practice trials were completed, the children were given 36 test trials during which we presented four different types of stimulus pairs. These pairs were (a) aligned–same, where the top halves of the two composite faces depicted the same identity (e.g., AA and AB) and where the top and bottom halves were horizontally aligned, (b) aligned–different, where the top halves of two composite faces depicted different identities (e.g., BA and AB) and where the top and bottom halves were horizontally aligned, (c) misaligned–same, where the top halves of two composite faces depicted the same identity but were horizontally offset, and (d) misaligned–different, where the top halves of two composite faces depicted different identities but were horizontally offset (Fig. 1A, right). Fig. 1B shows an example of the types of stimuli and response buttons presented during an aligned–same trial.

### Analysis Plan

"Response accuracy
The data of primary interest were the accuracy scores obtained in the same trials. Specifically, lower
accuracy scores in the aligned–same trials than in the misaligned–same trials is generally considered to
reflect holistic processing. The data of secondary interest were the accuracy scores obtained in the
different trials. In this case, the accuracy scores in the aligned–different trials and in the misaligned–
different trials should be the same. These different trial scores indicate how well children were able
to detect differences when the top halves of the composite faces actually differed and, thus, provide
a baseline against which to evaluate the accuracy data from the same trials. To statistically assess
response accuracy, we performed mixed repeated-measures analysis of variance (ANOVA) models with
alignment as a within-participants factor, age and gender as between-participants factors, and partic-
ipant as a random effect. For all analyses, we included gender as a predictor given prior research show-
ing that there may be differences in holistic face processing even in early childhood (Stajduhar et al.,
2022).
Same trials. Fig. 2 shows the accuracy scores in the same trials, and it can be seen that the predicted
effect was present at each age. That is, at each age children exhibited lower accuracy scores when the
same top halves of a face were aligned with the bottom halves of two different faces than when they
were misaligned. A mixed repeated-measures ANOVA of the accuracy scores.""

### Differences from Original Study

Although I have used the same face database (Chicago Face Database) for my study, the stimuli was different in a sense that since we doubled the trial number from the original study, I will use double the stimuli number. Yates and Lewkowicz presented 24 pairs of composite face stimuli to each participant, and i plan to present 48 pairs (24 female composite faces and 24 male composite faces.)

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
